# Generated by Django 5.2.7 on 2025-10-10 22:32

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_journalentry_journalline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- Новые модели ---
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True)),
                ("debit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("credit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
            ],
            options={
                "verbose_name": "Hesap Bakiye (Aylık)",
                "verbose_name_plural": "Hesap Bakiyeleri (Aylık)",
                "ordering": ["-year", "-month", "account__code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Muhasebe Dönemi",
                "verbose_name_plural": "Muhasebe Dönemleri",
                "ordering": ["-year", "-month"],
            },
        ),

        # --- Изменения опций моделей ---
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["code"], "verbose_name": "Hesap", "verbose_name_plural": "Hesaplar"},
        ),
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-date", "-id"], "verbose_name": "Yevmiye Kaydı", "verbose_name_plural": "Yevmiye Kayıtları"},
        ),
        migrations.AlterModelOptions(
            name="journalline",
            options={"ordering": ["entry_id", "line_no", "id"], "verbose_name": "Yevmiye Satırı", "verbose_name_plural": "Yevmiye Satırları"},
        ),

        # --- Поля Account ---
        migrations.AddField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="core.account",
                help_text="İsteğe bağlı: üst hesap",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("AS", "Varlık"), ("LI", "Yükümlülük"), ("EQ", "Öz Kaynak"), ("IN", "Gelir"), ("EX", "Gider")],
                default="AS",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                db_index=True,
                help_text="Örn: 100, 102, 320, 500",
                validators=[django.core.validators.RegexValidator(r"^\d{3,6}$", "Kod 3-6 rakam olmalı")],
            ),
        ),

        # --- Поля JournalEntry ---
        migrations.AddField(
            model_name="journalentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journalentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="status",
            field=models.CharField(choices=[("D", "Taslak"), ("P", "Onaylı")], default="D", max_length=1),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="date",
            field=models.DateField(db_index=True),
        ),

        # --- Поля JournalLine ---
        migrations.AddField(
            model_name="journalline",
            name="line_no",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="debit",
            field=models.DecimalField(
                max_digits=16, decimal_places=2, default=Decimal("0.00"),
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="journalline",
            name="credit",
            field=models.DecimalField(
                max_digits=16, decimal_places=2, default=Decimal("0.00"),
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),

        # --- Индексы ---
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["code"], name="core_accoun_code_463b29_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["type"], name="core_accoun_type_92c2c4_idx"),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["date", "status"], name="core_journa_date_01a6f4_idx"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["entry", "account"], name="core_journa_entry_i_1525e4_idx"),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(fields=["account"], name="core_journa_account_04bec6_idx"),
        ),

        # --- CHECK-ограничения для JournalLine ---
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                name="chk_no_both_positive_debit_credit",
                condition=models.Q(models.Q(("debit__gt", 0), _negated=True), ("credit", 0), _connector="OR"),
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                name="chk_no_both_positive_credit_debit",
                condition=models.Q(models.Q(("credit__gt", 0), _negated=True), ("debit", 0), _connector="OR"),
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                name="chk_must_have_amount",
                condition=models.Q(("debit__gt", 0), ("credit__gt", 0), _connector="OR"),
            ),
        ),

        # --- Внешние ключи/уникальности для новых моделей ---
        migrations.AddField(
            model_name="accountbalance",
            name="account",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.account"),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalperiod",
            unique_together={("year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="accountbalance",
            unique_together={("account", "year", "month")},
        ),
    ]
